### ISSUE TITLE
DioException 302 Error

### ISSUE THREAD

**Issue by shadowdraon319** [faithoflifedev/google_vision_workspace#10]
Exception has occurred.
DioException (DioException [bad response]: The request returned an invalid status code of 302.)

The error is in the oauth.g.dart file. It was working yesterday, but doesn't seem to work today.

**Comment by faithoflifedev** [comment]
@shadowdraon319, you haven't provided any information that would allow someone to troubleshoot an issue.

I've published an updated version of the package because I noticed that the flutter example did not run when I tried it - [google_vision: ^1.0.8+4](https://pub.dev/packages/google_vision).

In addition, I've updated the `retrofit_generator` dependency.  But, nothing related to `Dio`.  

If you could provide some sample code that would allow for recreation of the issue your experiencing, then I might be able to help.

**Comment by shadowdraon319** [comment]
This is the code snippet I am using. When called it crashes and states: Exception has occurred.
DioException (DioException [bad response]: The request returned an invalid status code of 302.)

The error is in the oauth.g.dart file.


Future<void> processTextImage(String imagePath) async {
    // Load your Google Cloud credentials (Service Account Key)
    final jwtFromAsset = await getFileFromAsset('splash-scanner.json');

    final googleVision = await gv.GoogleVision.withJwt(jwtFromAsset);

    final image = gv.Painter.fromFilePath(imagePath);

    final requests = gv.AnnotationRequests(requests: [
      gv.AnnotationRequest(image: gv.Image(painter: image), features: [
        gv.Feature(maxResults: 10, type: 'DOCUMENT_TEXT_DETECTION'),
      ])
    ]);

    final annotatedResponses = await googleVision.annotate(requests: requests);

    var text = '';

    for (var annotatedResponse in annotatedResponses.responses) {
      var first = true;
      for (var textAnnotation in annotatedResponse.textAnnotations) {
        if (first) {
          text += textAnnotation.description + '\n';
          first = false;
        }
      }
    }

    // Making API request to OpenAI with detected text
    var parsedFields = await parseFormFieldsWithOpenAI(text);

    // Display the parsed fields and responses side by side
    setState(() {
      _detectedText = parsedFields;
    });
  }

**Comment by faithoflifedev** [comment]
@shadowdraon319, does the provided flutter example work for you?  See instructions at the bottom of this page after checking out the code - https://github.com/faithoflifedev/google_vision/blob/main/example/example.md - Also are you running the most up to date release of the package?

**Comment by shadowdraon319** [comment]
Yes, I am using the most up to date version. The example does not work either. The only change was that it was working perfectly and then I updated flutter and it no longer works. It gives a http certificate invalid error  [https://stackoverflow.com/questions/72700742/unhandled-exception-handshakeexception-handshake-error-in-client-os-error-ce](https://stackoverflow.com/questions/72700742/unhandled-exception-handshakeexception-handshake-error-in-client-os-error-ce) resolved by this and then the 302 error occurs. It's really weird because a 302 error is for redirects for the api call though so shouldn't impact it. Maybe it is due to certificates? What flutter/dart version are you using?

**Comment by faithoflifedev** [comment]
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.79.2)

Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "macos_arm64"
```

**Comment by shadowdraon319** [comment]
Thank you for your help in resolving. It was an issue with my internet connection. I appreciate the effort!
