### ISSUE TITLE
Using API key to Authenticating

### ISSUE THREAD

**Issue by w830207** [faithoflifedev/google_vision_workspace#19]
API key is much simper to use
https://cloud.google.com/vision/product-search/docs/auth#using_an_api_key
 😉🙏

**Comment by faithoflifedev** [comment]
@w830207 updates have been published as follows:

google_vision_flutter: 1.0.0+3
google_vision: 1.2.1

The updated packages make use of `GoogleVision.withApiKey(String apiKey)` to authenticate.

Keep in mind that it would be a bad idea to have the apiKey hard coded in your app.
