### ISSUE TITLE
hi，can documentTextDetection  change language？

### ISSUE THREAD

**Issue by iOSyan** [faithoflifedev/google_vision_workspace#21]
Can documentTextDetection  change language？ thanks！

**Comment by faithoflifedev** [comment]
Hi @iOSyan,

The Google Vision Api docs have the answer.

https://cloud.google.com/vision/docs/ocr#specify_the_language_optional

```json
{
  "requests": [
    {
      "image": {
        "source": {
          "imageUri": "IMAGE_URL"
        }
      },
      "features": [
        {
          "type": "DOCUMENT_TEXT_DETECTION"
        }
      ],
      "imageContext": {
        "languageHints": ["en-t-i0-handwrit"]
      }
    }
  ]
}
```

The package equivalent documentation for the `ImageContext` class is - https://pub.dev/documentation/google_vision/latest/google_vision/ImageContext-class.html
