### ISSUE TITLE
Missing Block parameter for FullTextAnnotation -> Page model

### ISSUE THREAD

**Issue by dondonj** [faithoflifedev/google_vision_workspace#22]
![image](https://github.com/faithoflifedev/google_vision_workspace/assets/48314079/08129aad-c912-4e5f-b6c7-a5657a58101d)

In the latest version, we don't have list of block parameter even though the api returns the list of blocks for FullTextAnnotation

**Comment by faithoflifedev** [comment]
Hi @dondonj ,

Which version are you looking at?  The latest version [google_vision: ^1.2.1+1](https://pub.dev/packages/google_vision) does have `Block`s as shown in the source - https://github.com/faithoflifedev/google_vision_workspace/blob/main/packages/google_vision/lib/src/model/page.dart

The code for the `Block` model can be seen here - https://github.com/faithoflifedev/google_vision_workspace/blob/main/packages/google_vision/lib/src/model/block.dart
