### ISSUE TITLE
API Key Restriction Issue: 403 Errors 

### ISSUE THREAD

**Issue by iOSyan** [faithoflifedev/google_vision_workspace#23]
In Google Cloud, within the API key settings, if I set 'Set an application restriction' to 'none,' the key works and returns results as expected. However, if I choose 'iOS' or 'Android' and configure the package name and SHA-1 certificate fingerprint, the calls fail and return a 403 error.

**Comment by faithoflifedev** [comment]
Hello @iOSyan, 

What you're describing doesn't sound like an issue with the package itself.  I don't think I can help you here.

**Comment by iOSyan** [comment]
Thank you for the reply. I checked, and if restrictions are needed, corresponding fields need to be added in the request headers. Can this library add headers?

```swift
request.addValue("com.xxx.xxx", forHTTPHeaderField: "X-Ios-Bundle-Identifier")

**Comment by faithoflifedev** [comment]
@iOSyan, give the following a try:

```dart
final googleVision =
    await GoogleVision.withApiKey('[your api key]');

// add a custom header
googleVision.dio.options.headers['com.xxx.xxx'] = 'X-Ios-Bundle-Identifier';

print('checking...');

final faceAnnotationResponses = await googleVision.faceDetection(
  JsonImage.fromFilePath('sample_image/young-man-smiling-and-thumbs-up.jpg'));

for (var faceAnnotation in faceAnnotationResponses) {
  print('Face - ${faceAnnotation.detectionConfidence}');

  print('Joy - ${faceAnnotation.enumJoyLikelihood}');
}

print('done.');
```

**Comment by iOSyan** [comment]
Thank you very much!

**Comment by faithoflifedev** [comment]
@iOSyan , with google_vision: ^1.2.1+2

You can use the following:

```dart
final googleVision =
    await GoogleVision.withApiKey(
        '[your api key]', 
        additionalHeaders: {'com.xxx.xxx': 'X-Ios-Bundle-Identifier'},
    );
```

**Comment by devsideal** [comment]
You can use the package [google_api_headers](https://pub.dev/packages/google_api_headers) then use like this:

```
final headers = await GoogleApiHeaders().getHeaders();
final googleVision =
    await GoogleVision.withApiKey(
        '[your api key]', 
        additionalHeaders: headers,
    );
```
