### ISSUE TITLE
How can we detect text in pdf file?

### ISSUE THREAD

**Issue by alisabry22** [faithoflifedev/google_vision_workspace#24]
Hello all ,

hopefully you help me on this is there any thing to detect text in pdfs because I see only JsonImage in parameters.

thank you.

**Comment by faithoflifedev** [comment]
Hello @alisabry22 ,

Currently the package does not support detecting text in a PDF.  At this time the package will only do detection in images as outlined in the `images:annotate` portion of the REST API - https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate - the types of image supported are: JPG, PNG, GIF, and TIFF.

I may add the `files:annotate` API at some point in the future - https://cloud.google.com/vision/docs/reference/rest/v1/files/annotate - which supports  "application/pdf", "image/tiff" and "image/gif"
