### ISSUE TITLE
Face Detection Enum Decoding

### ISSUE THREAD

**Issue by husitawi** [faithoflifedev/google_vision_workspace#7]
Resulting Face Annotations are misbehaving, I did some debugging and I think the decoding function is the problem since we're comparing the enum VALUE instead of the KEY to the returned value from Google Vision. This is resulting in LikeLihood.UNKNOWN all the time.
<img width="1307" alt="Screenshot 2023-03-09 at 12 15 31 PM" src="https://user-images.githubusercontent.com/26905155/223992652-916dd42c-2876-406c-bb9e-4919888013a4.png">

**Comment by husitawi** [comment]
Follow up, just changing the face_annotations Likelihood enum to the following fixes the issue.

@JsonEnum()
enum Likelihood {
  @JsonValue('UNKNOWN')
  UNKNOWN,
  @JsonValue('VERY_UNLIKELY')
  VERY_UNLIKELY,
  @JsonValue('UNLIKELY')
  UNLIKELY,
  @JsonValue('POSSIBLE')
  POSSIBLE,
  @JsonValue('LIKELY')
  LIKELY,
  @JsonValue('VERY_LIKELY')
  VERY_LIKELY
}

**Comment by faithoflifedev** [comment]
Hi @husitawi , Release v1.0.7+6 has the above changes.
