### ISSUE TITLE
SafeSearchAnnotation Json Response Object Name Incorrect

### ISSUE THREAD

**Issue by kamaribedwarddev** [faithoflifedev/google_vision_workspace#8]
The Json response object name for SafeSearchAnnotation should be "safeSearchAnnotation".

 safeSearchAnnotation: json['**safeSearchAnnotations**'] == null
          ? null
          : SafeSearchAnnotation.fromJson(
              json['**safeSearchAnnotations**'] as Map<String, dynamic>),

**Comment by faithoflifedev** [comment]
@kamaribedwarddev, fixed in new release `google_vision` 1.0.7+7
