### ISSUE TITLE
Video security 

### ISSUE THREAD

**Issue by jack-fan1991** [faithoflifedev/google_vision_workspace#9]
I want to build an app that allows users to upload videos. How can I use a package to filter the security of videos?

**Comment by faithoflifedev** [comment]
Hello @jack-fan1991,

This is not really the forum for general how-to questions.  I recommend [reddit](https://www.reddit.com/r/FlutterDev/) or maybe ChatGPT for that.

If you have a more specific question about some aspect of the functionality, like "Why does method `X` work this way?", then I could probably help.
